"""empty message

Revision ID: 1ca5473ebe0d
Revises: 4ea0f1d728b7
Create Date: 2020-01-07 21:17:01.547000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca5473ebe0d'
down_revision = '4ea0f1d728b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotteries', sa.Column('bonous', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lotteries', 'bonous')
    # ### end Alembic commands ###
