"""empty message

Revision ID: 20f0b105765c
Revises: 1ca5473ebe0d
Create Date: 2020-01-08 14:47:39.937166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f0b105765c'
down_revision = '1ca5473ebe0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lotteries_id', table_name='lotteries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_lotteries_id', 'lotteries', ['id'], unique=False)
    # ### end Alembic commands ###
