"""empty message

Revision ID: 4ea0f1d728b7
Revises: 
Create Date: 2020-01-07 21:09:04.533411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea0f1d728b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotteries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('red1', sa.Integer(), nullable=True),
    sa.Column('red2', sa.Integer(), nullable=True),
    sa.Column('red3', sa.Integer(), nullable=True),
    sa.Column('red4', sa.Integer(), nullable=True),
    sa.Column('red5', sa.Integer(), nullable=True),
    sa.Column('red6', sa.Integer(), nullable=True),
    sa.Column('blue', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lotteries')
    # ### end Alembic commands ###
